main:
  experiment_name_prefix: my_exp
  seed: 1
  num_workers: 6
  parallel: False
  gpus_to_use: 1,2
  trains: False
  paths:
    train: 'data/train.json'
    validation: 'data/validation.json'
    logs: 'logs/'
train:
  num_epochs: 15
  grad_clip: 0.25
  dropout: 0.2
  num_hid: 256
  batch_size: 256
  save_model: True
  lr:
    lr_value: 1e-3
    lr_decay: 15
    lr_gamma: 0.1
    lr_step_size: 30